security:
    # Encodage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseur d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Hiérarchie des rôles
    role_hierarchy:
        ROLE_BIBLIOTHECAIRE: [ROLE_USER]
        ROLE_ADMIN:          [ROLE_BIBLIOTHECAIRE]

    # Pare-feu
    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            
            # Login
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_livre_index # J'ai mis le catalogue en accueil après login

            # Logout
            logout:
                path: app_logout
                target: app_login

            # Optionnel : Se souvenir de moi
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine

    # --- C'EST ICI QUE TOUT SE JOUE ---
    access_control:
        # 1. PROTECTION ADMINISTRATION (Ajout / Modif)
        # Seul le bibliothécaire peut accéder à /livre/new et /livre/edit
        - { path: ^/livre/new, roles: ROLE_BIBLIOTHECAIRE }
        - { path: ^/livre/\d+/edit, roles: ROLE_BIBLIOTHECAIRE }
        - { path: ^/admin, roles: ROLE_ADMIN }

        # 2. PROTECTION UTILISATEUR (Panier / Commandes / Téléchargement)
        # Il faut être connecté pour voir son panier ou ses achats
        - { path: ^/cart, roles: ROLE_USER }
        - { path: ^/mes-demandes, roles: ROLE_USER }
        - { path: ^/livre/\d+/telecharger, roles: ROLE_USER }

        # 3. PUBLIC (Tout le reste)
        # Login, Register, Catalogue (Index) et Détails livre restent accessibles
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        # Cette dernière règle laisse passer tout le reste (Catalogue, Accueil...)
        - { path: ^/, roles: PUBLIC_ACCESS }