security:
    # Encodage des mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseur d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Hiérarchie des rôles (C'est ici que la magie opère !)
    # L'ADMIN hérite automatiquement des droits du BIBLIOTHECAIRE
    role_hierarchy:
        ROLE_BIBLIOTHECAIRE: [ROLE_USER]
        ROLE_ADMIN:          [ROLE_BIBLIOTHECAIRE]

    # Pare-feu
    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            
            # Login
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_home # Redirection après login

            # Logout
            logout:
                path: app_logout
                target: app_login

            # Optionnel : Se souvenir de moi
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine

    # Contrôle d'accès
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # On laisse l'accueil, le login et le register ouverts à tous
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }